// The plumbing under .github/, checked without a YAML parser (zero
// dependencies). These are not style assertions: each one is a finding from
// docs/review-2026-09-01.md that would be invisible until the day it bit.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { ROOT } from './helpers.mjs';

const WORKFLOWS = path.join(ROOT, '.github', 'workflows');
const TEMPLATES = path.join(ROOT, '.github', 'ISSUE_TEMPLATE');

const read = (dir, name) => readFile(path.join(dir, name), 'utf8');

// Every line of every `run:` block, with the file and line it came from.
function runLines(text) {
  const lines = text.split('\n');
  const out = [];
  let indent = null;
  lines.forEach((line, i) => {
    if (indent !== null) {
      const width = line.length - line.trimStart().length;
      if (line.trim() === '' || width > indent) {
        out.push({ line, number: i + 1 });
        return;
      }
      indent = null;
    }
    const match = /^(\s*)(?:- )?run:\s*(.*)$/.exec(line);
    if (match) {
      if (match[2] && match[2] !== '|' && match[2] !== '>') out.push({ line: match[2], number: i + 1 });
      indent = match[1].length;
    }
  });
  return out;
}

test('no workflow interpolates anything into a shell command', async () => {
  // ${{ }} inside run: is shell injection the day an issue body reaches it,
  // with a token that can push (finding 8). Values arrive through env:.
  for (const name of await readdir(WORKFLOWS)) {
    const text = await read(WORKFLOWS, name);
    for (const { line, number } of runLines(text)) {
      assert.ok(!line.includes('${{'), `${name}:${number} interpolates into a shell command: ${line.trim()}`);
    }
  }
});

test('contribution.yml runs only on the maintainer label, with the scoped PAT', async () => {
  const text = await read(WORKFLOWS, 'contribution.yml');
  assert.match(text, /on:\s*\n\s*issues:\s*\n\s*types:\s*\[labeled\]/);
  assert.match(text, /if:\s*github\.event\.label\.name == 'accepted'/);
  assert.match(text, /secrets\.CONTRIBUTION_PAT/);
  // Absent secret: a clear message, not a mysterious 403 halfway through.
  assert.match(text, /if \[ -z "\$PAT" \]; then/);
  assert.match(text, /::error::The repository secret CONTRIBUTION_PAT is not set\./);
  // The checkout, the push and the PR all use the PAT: a PR opened with
  // GITHUB_TOKEN gets no CI at all (finding 2).
  assert.match(text, /token: \$\{\{ secrets\.CONTRIBUTION_PAT \}\}/);
  assert.match(text, /GH_TOKEN: \$\{\{ secrets\.CONTRIBUTION_PAT \}\}/);
  assert.match(text, /ISSUE_BODY: \$\{\{ github\.event\.issue\.body \}\}/);
  assert.match(text, /node tools\/bundle-to-files\.mjs --correction/);
  assert.match(text, /node tools\/validate\.mjs/);
  assert.match(text, /gh pr create/);
  assert.match(text, /branch, commit and push/i);
  assert.match(text, /if: failure\(\)/);
  // The catalogue lookup is a reading aid and never fails the run.
  assert.match(text, /continue-on-error: true/);
});

test('the index is owned by main, and pull requests never carry it', async () => {
  const validate = await read(WORKFLOWS, 'validate.yml');
  assert.match(validate, /on:\s*\n\s*pull_request:/);
  assert.doesNotMatch(validate, /build-index|--index/);
  const deploy = await read(WORKFLOWS, 'deploy.yml');
  assert.match(deploy, /concurrency:\s*\n\s*group: deploy\s*\n\s*cancel-in-progress: false/);
  assert.match(deploy, /node tools\/build-index\.mjs/);
  assert.match(deploy, /node tools\/validate\.mjs --index/);
  // One job: build the index, commit it, upload that same checkout, deploy.
  // Two jobs would deploy a checkout that does not carry the index it built.
  const jobs = deploy.slice(deploy.indexOf('\njobs:'));
  assert.deepEqual(jobs.match(/^ {2}[a-z-]+:$/gm), ['  deploy:']);
});

test('both issue templates take a bundle and require the licence grant', async () => {
  const names = (await readdir(TEMPLATES)).sort();
  assert.deepEqual(names, ['config.yml', 'contribution.yml', 'correction.yml']);
  assert.match(await read(TEMPLATES, 'config.yml'), /blank_issues_enabled: false/);
  for (const name of ['contribution.yml', 'correction.yml']) {
    const text = await read(TEMPLATES, name);
    assert.match(text, /^ {4}id: bundle$/m, `${name} has one textarea called bundle`);
    assert.match(text, /labels: \["contribution"/, `${name} auto-applies a label that triggers nothing`);
    assert.match(text, /CC BY-SA 4\.0/, `${name} states the licence grant`);
    assert.match(text, /generated by a language model/, `${name} asks for the text to be the contributor's own`);
    // Three required checkboxes plus the required textarea.
    assert.ok((text.match(/required: true/g) ?? []).length >= 4, `${name} makes the grant required`);
    assert.doesNotMatch(text, /^\s*render:/m, `${name}: a rendered textarea cannot be trusted with URL prefill`);
  }
  assert.match(await read(TEMPLATES, 'correction.yml'), /labels: \["contribution", "correction"\]/);
});

test('the review checklist and CODEOWNERS still cover data and the plumbing', async () => {
  const template = await readFile(path.join(ROOT, '.github', 'PULL_REQUEST_TEMPLATE.md'), 'utf8');
  assert.match(template, /written by a person/);
  const owners = await readFile(path.join(ROOT, '.github', 'CODEOWNERS'), 'utf8');
  assert.match(owners, /^\/data\//m);
  assert.match(owners, /^\/\.github\//m);
});
